version: '3.3'

services:
  postgres:
    image: postgres:12.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: postgres
